package dal;
// Generated 17-dec-2014 14:52:24 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Babyspullen generated by hbm2java
 */
public class Babyspullen implements java.io.Serializable {

    private Integer id;
    private Persoon persoon;
    private String titel;
    private Boolean geslacht;
    private Integer leeftijd;
    private String categorie;
    private String omschrijving;
    private byte[] babyspullenFoto;
    private Set advertenties = new HashSet(0);

    public Babyspullen() {
    }

    public Babyspullen(Integer id, Persoon persoon, String titel, Boolean geslacht, Integer leeftijd, String categorie, String omschrijving, byte[] babyspullenFoto) {
        this.id = id;
        this.persoon = persoon;
        this.titel = titel;
        this.geslacht = geslacht;
        this.leeftijd = leeftijd;
        this.categorie = categorie;
        this.omschrijving = omschrijving;
        this.babyspullenFoto = babyspullenFoto;
    }

    public Babyspullen(Persoon persoon) {
        this.persoon = persoon;
    }

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the persoon
     */
    public Persoon getPersoon() {
        return persoon;
    }

    /**
     * @param persoon the persoon to set
     */
    public void setPersoon(Persoon persoon) {
        this.persoon = persoon;
    }

    /**
     * @return the titel
     */
    public String getTitel() {
        return titel;
    }

    /**
     * @param titel the titel to set
     */
    public void setTitel(String titel) {
        this.titel = titel;
    }

    /**
     * @return the geslacht
     */
    public Boolean getGeslacht() {
        return geslacht;
    }

    /**
     * @param geslacht the geslacht to set
     */
    public void setGeslacht(Boolean geslacht) {
        this.geslacht = geslacht;
    }

    /**
     * @return the leeftijd
     */
    public Integer getLeeftijd() {
        return leeftijd;
    }

    /**
     * @param leeftijd the leeftijd to set
     */
    public void setLeeftijd(Integer leeftijd) {
        this.leeftijd = leeftijd;
    }

    /**
     * @return the categorie
     */
    public String getCategorie() {
        return categorie;
    }

    /**
     * @param categorie the categorie to set
     */
    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }

    /**
     * @return the omschrijving
     */
    public String getOmschrijving() {
        return omschrijving;
    }

    /**
     * @param omschrijving the omschrijving to set
     */
    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }

    /**
     * @return the babyspullenFoto
     */
    public byte[] getBabyspullenFoto() {
        return babyspullenFoto;
    }

    /**
     * @param babyspullenFoto the babyspullenFoto to set
     */
    public void setBabyspullenFoto(byte[] babyspullenFoto) {
        this.babyspullenFoto = babyspullenFoto;
    }

    /**
     * @return the advertenties
     */
    public Set getAdvertenties() {
        return advertenties;
    }

    /**
     * @param advertenties the advertenties to set
     */
    public void setAdvertenties(Set advertenties) {
        this.advertenties = advertenties;
    }

    public String geefPersoon() {
        return persoon.getFamilienaam() + " " + persoon.getVoornaam();
    }

}
