package dal;
// Generated 17-dec-2014 14:52:24 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Kleren generated by hbm2java
 */
public class Kleren implements java.io.Serializable {

    private Integer id;
    private Persoon persoon;
    private Boolean geslacht;
    private String maat;
    private String soortKleding;
    private String seizoen;
    private String omschrijving;
    private byte[] klerenFoto;
    private Set advertenties = new HashSet(0);

    public Kleren() {
    }

    public Kleren(Persoon persoon) {
        this.persoon = persoon;
    }

    public Kleren(Persoon persoon, Boolean geslacht, String maat, String soortKleding, String seizoen, String omschrijving, byte[] klerenFoto, Set advertenties) {
        this.persoon = persoon;
        this.geslacht = geslacht;
        this.maat = maat;
        this.soortKleding = soortKleding;
        this.seizoen = seizoen;
        this.omschrijving = omschrijving;
        this.klerenFoto = klerenFoto;
        this.advertenties = advertenties;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Persoon getPersoon() {
        return persoon;
    }

    public void setPersoon(Persoon persoon) {
        this.persoon = persoon;
    }

    public Boolean getGeslacht() {
        return this.geslacht;
    }

    public void setGeslacht(Boolean geslacht) {
        this.geslacht = geslacht;
    }

    public String getMaat() {
        return this.maat;
    }

    public void setMaat(String maat) {
        this.maat = maat;
    }

    public String getSoortKleding() {
        return this.soortKleding;
    }

    public void setSoortKleding(String soortKleding) {
        this.soortKleding = soortKleding;
    }

    public String getSeizoen() {
        return this.seizoen;
    }

    public void setSeizoen(String seizoen) {
        this.seizoen = seizoen;
    }

    public String getOmschrijving() {
        return this.omschrijving;
    }

    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }

    public byte[] getKlerenFoto() {
        return this.klerenFoto;
    }

    public void setKlerenFoto(byte[] klerenFoto) {
        this.klerenFoto = klerenFoto;
    }

    public Set getAdvertenties() {
        return this.advertenties;
    }

    public void setAdvertenties(Set advertenties) {
        this.advertenties = advertenties;
    }

    public String geefPersoon() {
        return persoon.getFamilienaam() + " " + persoon.getVoornaam();
    }

}
