package dal;
// Generated 17-dec-2014 14:52:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persoon generated by hbm2java
 */
public class Persoon  implements java.io.Serializable {


     private Integer id;
     private String voornaam;
     private String familienaam;
     private String aanspreekTitel;
     private String email;
     private String woonPlaats;
     private String userName;
     private String passWord;
     private Set klerens = new HashSet(0);
     private Set advertenties = new HashSet(0);
     private Set boekens = new HashSet(0);
     private Set speelgoeds = new HashSet(0);
     private Set babyspullens = new HashSet(0);

    public Persoon() {
    }

	
    public Persoon(String aanspreekTitel, String woonPlaats) {
        this.aanspreekTitel = aanspreekTitel;
        this.woonPlaats = woonPlaats;
    }
    public Persoon(String voornaam, String familienaam, String aanspreekTitel, String email, String woonPlaats, String userName, String passWord, Set klerens, Set advertenties, Set boekens, Set speelgoeds, Set babyspullens) {
       this.voornaam = voornaam;
       this.familienaam = familienaam;
       this.aanspreekTitel = aanspreekTitel;
       this.email = email;
       this.woonPlaats = woonPlaats;
       this.userName = userName;
       this.passWord = passWord;
       this.klerens = klerens;
       this.advertenties = advertenties;
       this.boekens = boekens;
       this.speelgoeds = speelgoeds;
       this.babyspullens = babyspullens;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVoornaam() {
        return this.voornaam;
    }
    
    public void setVoornaam(String voornaam) {
        this.voornaam = voornaam;
    }
    public String getFamilienaam() {
        return this.familienaam;
    }
    
    public void setFamilienaam(String familienaam) {
        this.familienaam = familienaam;
    }
    public String getAanspreekTitel() {
        return this.aanspreekTitel;
    }
    
    public void setAanspreekTitel(String aanspreekTitel) {
        this.aanspreekTitel = aanspreekTitel;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWoonPlaats() {
        return this.woonPlaats;
    }
    
    public void setWoonPlaats(String woonPlaats) {
        this.woonPlaats = woonPlaats;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassWord() {
        return this.passWord;
    }
    
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }
    public Set getKlerens() {
        return this.klerens;
    }
    
    public void setKlerens(Set klerens) {
        this.klerens = klerens;
    }
    public Set getAdvertenties() {
        return this.advertenties;
    }
    
    public void setAdvertenties(Set advertenties) {
        this.advertenties = advertenties;
    }
    public Set getBoekens() {
        return this.boekens;
    }
    
    public void setBoekens(Set boekens) {
        this.boekens = boekens;
    }
    public Set getSpeelgoeds() {
        return this.speelgoeds;
    }
    
    public void setSpeelgoeds(Set speelgoeds) {
        this.speelgoeds = speelgoeds;
    }
    public Set getBabyspullens() {
        return this.babyspullens;
    }
    
    public void setBabyspullens(Set babyspullens) {
        this.babyspullens = babyspullens;
    }

}


