package BO;
// Generated 14-jan-2015 10:24:43 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Advertentie generated by hbm2java
 */
public class Advertentie  implements java.io.Serializable {


     private Integer id;
     private Babyspullen babyspullen;
     private Boeken boeken;
     private Kleren kleren;
     private Persoon persoon;
     private Date insertedOn;

    public Advertentie() {
    }

    public Advertentie(Babyspullen babyspullen, Boeken boeken, Kleren kleren, Persoon persoon, Date insertedOn) {
       this.babyspullen = babyspullen;
       this.boeken = boeken;
       this.kleren = kleren;
       this.persoon = persoon;
       this.insertedOn = insertedOn;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Babyspullen getBabyspullen() {
        return this.babyspullen;
    }
    
    public void setBabyspullen(Babyspullen babyspullen) {
        this.babyspullen = babyspullen;
    }
    public Boeken getBoeken() {
        return this.boeken;
    }
    
    public void setBoeken(Boeken boeken) {
        this.boeken = boeken;
    }
    public Kleren getKleren() {
        return this.kleren;
    }
    
    public void setKleren(Kleren kleren) {
        this.kleren = kleren;
    }
    public Persoon getPersoon() {
        return this.persoon;
    }
    
    public void setPersoon(Persoon persoon) {
        this.persoon = persoon;
    }
    public Date getInsertedOn() {
        return this.insertedOn;
    }
    
    public void setInsertedOn(Date insertedOn) {
        this.insertedOn = insertedOn;
    }




}


