package BO;
// Generated 14-jan-2015 10:24:43 by Hibernate Tools 4.3.1

import java.util.*;
//import org.hibernate.*;
//import org.hibernate.Session;

/**
 * Persoon generated by hbm2java
 */
public class Persoon implements java.io.Serializable {

    private Integer id;
    private String voornaam;
    private String familienaam;
    private String aanspreekTitel;
    private String email;
    private String woonPlaats;
    private String userName;
    private String passWord;
    private Set klerens = new HashSet(0);
    private Set advertenties = new HashSet(0);
    private Set boekens = new HashSet(0);
    private Set speelgoeds = new HashSet(0);
    private Set babyspullens = new HashSet(0);

    public Persoon() {
    }

    @Override
    public String toString() {
        return getUserName();

    }

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the voornaam
     */
    public String getVoornaam() {
        return voornaam;
    }

    /**
     * @param voornaam the voornaam to set
     */
    public void setVoornaam(String voornaam) {
        this.voornaam = voornaam;
    }

    /**
     * @return the familienaam
     */
    public String getFamilienaam() {
        return familienaam;
    }

    /**
     * @param familienaam the familienaam to set
     */
    public void setFamilienaam(String familienaam) {
        this.familienaam = familienaam;
    }

    /**
     * @return the aanspreekTitel
     */
    public String getAanspreekTitel() {
        return aanspreekTitel;
    }

    /**
     * @param aanspreekTitel the aanspreekTitel to set
     */
    public void setAanspreekTitel(String aanspreekTitel) {
        this.aanspreekTitel = aanspreekTitel;
    }

    /**
     * @return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email the email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return the woonPlaats
     */
    public String getWoonPlaats() {
        return woonPlaats;
    }

    /**
     * @param woonPlaats the woonPlaats to set
     */
    public void setWoonPlaats(String woonPlaats) {
        this.woonPlaats = woonPlaats;
    }

    /**
     * @return the userName
     */
    public String getUserName() {
        return userName;
    }

    /**
     * @param userName the userName to set
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * @return the passWord
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * @param passWord the passWord to set
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

    /**
     * @return the klerens
     */
    public Set getKlerens() {
        return klerens;
    }

    /**
     * @param klerens the klerens to set
     */
    public void setKlerens(Set klerens) {
        this.klerens = klerens;
    }

    /**
     * @return the advertenties
     */
    public Set getAdvertenties() {
        return advertenties;
    }

    /**
     * @param advertenties the advertenties to set
     */
    public void setAdvertenties(Set advertenties) {
        this.advertenties = advertenties;
    }

    /**
     * @return the boekens
     */
    public Set getBoekens() {
        return boekens;
    }

    /**
     * @param boekens the boekens to set
     */
    public void setBoekens(Set boekens) {
        this.boekens = boekens;
    }

    /**
     * @return the speelgoeds
     */
    public Set getSpeelgoeds() {
        return speelgoeds;
    }

    /**
     * @param speelgoeds the speelgoeds to set
     */
    public void setSpeelgoeds(Set speelgoeds) {
        this.speelgoeds = speelgoeds;
    }

    /**
     * @return the babyspullens
     */
    public Set getBabyspullens() {
        return babyspullens;
    }

    /**
     * @param babyspullens the babyspullens to set
     */
    public void setBabyspullens(Set babyspullens) {
        this.babyspullens = babyspullens;
    }

}
