/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BO.Babyspullen;
import BO.Boeken;
import BO.Kleren;
import BO.Persoon;
import BO.Speelgoed;
import Services.BabyService;
import Services.BoekService;
import Services.KlerenService;
import Services.PersoonService;
import Services.SpeelgoedService;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Tom
 */
public class BeheerderUI1 extends javax.swing.JFrame {

    /**
     * Creates new form BeheerderUI1
     */
    public BeheerderUI1() {
        initComponents();
        ListboxOpvullen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelete2 = new javax.swing.JButton();
        btnAddGebruiker2 = new javax.swing.JButton();
        lblEmail2 = new javax.swing.JLabel();
        txtUserName2 = new javax.swing.JTextField();
        lblVoornaam2 = new javax.swing.JLabel();
        txtFamilieNaam2 = new javax.swing.JTextField();
        txtWoonplaats2 = new javax.swing.JTextField();
        lblUserName2 = new javax.swing.JLabel();
        lblAanspreekTitel2 = new javax.swing.JLabel();
        lblPassWord2 = new javax.swing.JLabel();
        txtEmail2 = new javax.swing.JTextField();
        lblFamilieNaam2 = new javax.swing.JLabel();
        lblWoonplaats2 = new javax.swing.JLabel();
        txtEditGebruiker3 = new javax.swing.JButton();
        txtPassWord2 = new javax.swing.JTextField();
        txtAanspreekTitel2 = new javax.swing.JTextField();
        txtVoornaam2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPersonen = new javax.swing.JList();
        btnSelectBaby = new javax.swing.JButton();
        lblAdvertentieUitgeverij = new javax.swing.JLabel();
        txtTitel = new javax.swing.JTextField();
        lblVoornaam = new javax.swing.JLabel();
        txtVoornaam = new javax.swing.JTextField();
        lblFamilieNaam = new javax.swing.JLabel();
        txtFamilieNaam = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblWoonplaats = new javax.swing.JLabel();
        txtWoonplaats = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassWord = new javax.swing.JLabel();
        txtPassWord = new javax.swing.JTextField();
        btnDeleteKleren = new javax.swing.JButton();
        btnEditPersoon = new javax.swing.JButton();
        btnAddPersoon = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstBoeken = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstBabySpullen = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstKleren = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstSpeelgoed = new javax.swing.JList();
        lblAanspreekTitel1 = new javax.swing.JLabel();
        txtAdvertentieUitgeverij = new javax.swing.JTextField();
        lblAanspreekTitel3 = new javax.swing.JLabel();
        lblAanspreekTitel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOmschrijving = new javax.swing.JTextArea();
        btnSelectFile = new javax.swing.JButton();
        lblAanspreekTitel5 = new javax.swing.JLabel();
        cbxGeslacht = new javax.swing.JComboBox();
        btnSelectPeroon = new javax.swing.JButton();
        btnSelectSpeelgoed = new javax.swing.JButton();
        btnSelectBoek = new javax.swing.JButton();
        btnSelectKleren = new javax.swing.JButton();
        btnVerwijderFoto = new javax.swing.JButton();
        btnClearPersoon = new javax.swing.JButton();
        lblGeslacht = new javax.swing.JLabel();
        txtAdvertentieTitel = new javax.swing.JTextField();
        lblAdvertentieCategorie = new javax.swing.JLabel();
        txtAdvertentieCategorie = new javax.swing.JTextField();
        lblAdvertentieAuteur2 = new javax.swing.JLabel();
        txtAdvertentieAuteur = new javax.swing.JTextField();
        btnFoto = new javax.swing.JButton();
        btnDeletePersoon = new javax.swing.JButton();
        btnDeleteBoek1 = new javax.swing.JButton();
        btnDeleteSpeelgoed = new javax.swing.JButton();
        btnDeleteBaby = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        btnDelete2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelete2.setText("Delete");
        btnDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPersoonActionPerformed(evt);
            }
        });

        btnAddGebruiker2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddGebruiker2.setText("Add");
        btnAddGebruiker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGebruiker2ActionPerformed(evt);
            }
        });

        lblEmail2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail2.setText("E-mail:");

        txtUserName2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblVoornaam2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVoornaam2.setText("Voornaam:");

        txtFamilieNaam2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtWoonplaats2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblUserName2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserName2.setText("Gebruiker naam:");

        lblAanspreekTitel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAanspreekTitel2.setText("Aanspreek Titel:");

        lblPassWord2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassWord2.setText("Wachtwoord:");

        txtEmail2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblFamilieNaam2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFamilieNaam2.setText("Familienaam");

        lblWoonplaats2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblWoonplaats2.setText("WoonPlaats:");

        txtEditGebruiker3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEditGebruiker3.setText("Edit");
        txtEditGebruiker3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteKlerenActionPerformed(evt);
            }
        });

        txtPassWord2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtAanspreekTitel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtVoornaam2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beheerder");
        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(1500, 800));
        getContentPane().setLayout(null);

        lstPersonen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(lstPersonen);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 251, 310);

        btnSelectBaby.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectBaby.setText("Select");
        btnSelectBaby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectBabyActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectBaby);
        btnSelectBaby.setBounds(590, 380, 79, 31);

        lblAdvertentieUitgeverij.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAdvertentieUitgeverij.setText("Uitgeverij:");
        getContentPane().add(lblAdvertentieUitgeverij);
        lblAdvertentieUitgeverij.setBounds(390, 590, 100, 22);

        txtTitel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtTitel);
        txtTitel.setBounds(140, 440, 190, 28);

        lblVoornaam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVoornaam.setText("Voornaam:");
        getContentPane().add(lblVoornaam);
        lblVoornaam.setBounds(10, 480, 86, 22);

        txtVoornaam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtVoornaam);
        txtVoornaam.setBounds(140, 480, 190, 28);

        lblFamilieNaam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFamilieNaam.setText("Familienaam:");
        getContentPane().add(lblFamilieNaam);
        lblFamilieNaam.setBounds(10, 520, 103, 22);

        txtFamilieNaam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtFamilieNaam);
        txtFamilieNaam.setBounds(140, 520, 190, 28);

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setText("E-mail:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(10, 560, 55, 22);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtEmail);
        txtEmail.setBounds(140, 560, 190, 28);

        lblWoonplaats.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblWoonplaats.setText("WoonPlaats:");
        getContentPane().add(lblWoonplaats);
        lblWoonplaats.setBounds(10, 600, 98, 22);

        txtWoonplaats.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtWoonplaats);
        txtWoonplaats.setBounds(140, 600, 190, 28);

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserName.setText("Gebruikersnaam:");
        getContentPane().add(lblUserName);
        lblUserName.setBounds(10, 640, 140, 22);

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtUserName);
        txtUserName.setBounds(140, 640, 190, 28);

        lblPassWord.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassWord.setText("Wachtwoord:");
        getContentPane().add(lblPassWord);
        lblPassWord.setBounds(10, 680, 104, 22);

        txtPassWord.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtPassWord);
        txtPassWord.setBounds(140, 680, 190, 28);

        btnDeleteKleren.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeleteKleren.setText("Delete");
        btnDeleteKleren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteKlerenActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteKleren);
        btnDeleteKleren.setBounds(980, 380, 90, 31);

        btnEditPersoon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditPersoon.setText("Edit");
        btnEditPersoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPersoonActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditPersoon);
        btnEditPersoon.setBounds(10, 720, 107, 31);

        btnAddPersoon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddPersoon.setText("Add");
        btnAddPersoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersoonActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddPersoon);
        btnAddPersoon.setBounds(130, 720, 100, 31);

        lblBackground.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblBackground.setText("Gebruikers Lijst");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(10, 20, 179, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Babyspullen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(580, 10, 220, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Boeken");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 10, 90, 60);

        lstBoeken.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane4.setViewportView(lstBoeken);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(280, 60, 290, 310);

        lstBabySpullen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane5.setViewportView(lstBabySpullen);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(580, 60, 290, 310);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Kleren");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(880, 20, 150, 50);

        lstKleren.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane6.setViewportView(lstKleren);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(880, 60, 290, 310);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Speelgoed");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1180, 20, 140, 50);

        lstSpeelgoed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane7.setViewportView(lstSpeelgoed);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(1180, 60, 290, 310);

        lblAanspreekTitel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAanspreekTitel1.setText("Aanspreek Titel:");
        getContentPane().add(lblAanspreekTitel1);
        lblAanspreekTitel1.setBounds(10, 440, 127, 22);

        txtAdvertentieUitgeverij.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtAdvertentieUitgeverij);
        txtAdvertentieUitgeverij.setBounds(480, 590, 190, 28);

        lblAanspreekTitel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAanspreekTitel3.setText("Titel:");
        getContentPane().add(lblAanspreekTitel3);
        lblAanspreekTitel3.setBounds(390, 470, 50, 22);

        lblAanspreekTitel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAanspreekTitel4.setText("Foto:");
        getContentPane().add(lblAanspreekTitel4);
        lblAanspreekTitel4.setBounds(1050, 440, 50, 22);

        txtOmschrijving.setColumns(20);
        txtOmschrijving.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtOmschrijving.setLineWrap(true);
        txtOmschrijving.setRows(5);
        jScrollPane2.setViewportView(txtOmschrijving);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(700, 470, 290, 190);

        btnSelectFile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectFile.setText("Kies een andere foto");
        btnSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFileActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectFile);
        btnSelectFile.setBounds(1060, 680, 220, 30);

        lblAanspreekTitel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAanspreekTitel5.setText("Omschrijving:");
        getContentPane().add(lblAanspreekTitel5);
        lblAanspreekTitel5.setBounds(700, 440, 130, 22);

        cbxGeslacht.setEditable(true);
        cbxGeslacht.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxGeslacht.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jongen", "Meisje" }));
        cbxGeslacht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGeslachtActionPerformed(evt);
            }
        });
        getContentPane().add(cbxGeslacht);
        cbxGeslacht.setBounds(480, 630, 120, 30);

        btnSelectPeroon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectPeroon.setText("Select");
        btnSelectPeroon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectPeroonActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectPeroon);
        btnSelectPeroon.setBounds(10, 380, 79, 31);

        btnSelectSpeelgoed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectSpeelgoed.setText("Select");
        btnSelectSpeelgoed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectSpeelgoedActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectSpeelgoed);
        btnSelectSpeelgoed.setBounds(1180, 380, 79, 31);

        btnSelectBoek.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectBoek.setText("Select");
        btnSelectBoek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectBoekActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectBoek);
        btnSelectBoek.setBounds(290, 380, 79, 31);

        btnSelectKleren.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectKleren.setText("Select");
        btnSelectKleren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectKlerenActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectKleren);
        btnSelectKleren.setBounds(890, 380, 79, 31);

        btnVerwijderFoto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVerwijderFoto.setText("Verwijder foto");
        btnVerwijderFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerwijderFotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerwijderFoto);
        btnVerwijderFoto.setBounds(1060, 720, 220, 30);

        btnClearPersoon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnClearPersoon.setText("Clear");
        btnClearPersoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPersoonActionPerformed(evt);
            }
        });
        getContentPane().add(btnClearPersoon);
        btnClearPersoon.setBounds(240, 720, 107, 31);

        lblGeslacht.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGeslacht.setText("Geslacht:");
        getContentPane().add(lblGeslacht);
        lblGeslacht.setBounds(390, 630, 100, 22);

        txtAdvertentieTitel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtAdvertentieTitel);
        txtAdvertentieTitel.setBounds(480, 470, 190, 28);

        lblAdvertentieCategorie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAdvertentieCategorie.setText("Categorie:");
        getContentPane().add(lblAdvertentieCategorie);
        lblAdvertentieCategorie.setBounds(390, 550, 90, 22);

        txtAdvertentieCategorie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtAdvertentieCategorie);
        txtAdvertentieCategorie.setBounds(480, 550, 190, 28);

        lblAdvertentieAuteur2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAdvertentieAuteur2.setText("Auteur:");
        getContentPane().add(lblAdvertentieAuteur2);
        lblAdvertentieAuteur2.setBounds(390, 510, 100, 22);

        txtAdvertentieAuteur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtAdvertentieAuteur);
        txtAdvertentieAuteur.setBounds(480, 510, 190, 28);

        btnFoto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFoto.setText("Geen afbeelding");
        btnFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnFoto.setFocusable(false);
        btnFoto.setRolloverEnabled(false);
        getContentPane().add(btnFoto);
        btnFoto.setBounds(1050, 470, 220, 200);

        btnDeletePersoon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeletePersoon.setText("Delete");
        btnDeletePersoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePersoonActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletePersoon);
        btnDeletePersoon.setBounds(90, 380, 90, 31);

        btnDeleteBoek1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeleteBoek1.setText("Delete");
        btnDeleteBoek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBoekActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteBoek1);
        btnDeleteBoek1.setBounds(380, 380, 90, 31);

        btnDeleteSpeelgoed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeleteSpeelgoed.setText("Delete");
        btnDeleteSpeelgoed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSpeelgoedActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteSpeelgoed);
        btnDeleteSpeelgoed.setBounds(1270, 380, 90, 31);

        btnDeleteBaby.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeleteBaby.setText("Delete");
        btnDeleteBaby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBabyActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteBaby);
        btnDeleteBaby.setBounds(680, 380, 90, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/vector1.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1920, 1200);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Persoon selectPersoon = new Persoon();
    Boeken selectBoek = new Boeken();
    Kleren selectKleren = new Kleren();
    Speelgoed selectSpeelgoed = new Speelgoed();
    Babyspullen selectBaby = new Babyspullen();
    
    private void ListboxOpvullen() {
        PersoonService p = new PersoonService();
        lstPersonen.setListData(p.AllePersonenOphalen().toArray());
    }
    
    private void BoekListOpvullen() {
        BoekService b = new BoekService();
        lstBoeken.setListData(b.SelecteerBoek(selectPersoon.getId()).toArray());
        
    }
    
    private void BabyListOpvullen() {
        BabyService ba = new BabyService();
        if (selectPersoon != null) {
            lstBabySpullen.setListData(ba.SelecteerBaby(selectPersoon.getId()).toArray());
        }
        
    }
    
    private void KlerenListOpvullen() {
        KlerenService k = new KlerenService();
        lstKleren.setListData(k.SelecteerKleren(selectPersoon.getId()).toArray());
        
    }
    
    private void SpeelgoedListOpvullen() {
        SpeelgoedService sp = new SpeelgoedService();
        lstSpeelgoed.setListData(sp.SelecteerSpeelgoed(selectPersoon.getId()).toArray());
        
    }
    
    private void ClearPersoon() {
        selectPersoon = null;
        txtTitel.setText(null);
        txtVoornaam.setText(null);
        txtVoornaam.setText(null);
        txtFamilieNaam.setText(null);
        txtEmail.setText(null);
        txtWoonplaats.setText(null);
        txtWoonplaats.setText(null);
        txtUserName.setText(null);
        txtPassWord.setText(null);
        
        lstBabySpullen.setListData(new Object[0]);
        lstBoeken.setListData(new Object[0]);
        lstKleren.setListData(new Object[0]);
        lstSpeelgoed.setListData(new Object[0]);
    }
    private void btnSelectBabyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectBabyActionPerformed
        txtAdvertentieAuteur.setText("leeftijd");
        lblAdvertentieUitgeverij.setVisible(false);
        selectBaby = (Babyspullen) lstBabySpullen.getSelectedValue();
        
        if (selectBaby.getGeslacht()) {
            cbxGeslacht.setSelectedIndex(0);
            
        } else {
            cbxGeslacht.setSelectedIndex(1);
        }
        
        if (selectBaby != null) {
            byte[] imageBytes;
            byte[] image = selectBaby.getBabyspullenFoto();
            ImageIcon icon = new ImageIcon(image);
            Babyspullen babyspullen = selectBaby;
            txtAdvertentieTitel.setText(selectBaby.getTitel());
            txtOmschrijving.setText(selectBaby.getOmschrijving());
            txtAdvertentieCategorie.setText(selectBaby.getCategorie());
            
            btnFoto.setIcon(icon);
        }
        
        txtAdvertentieAuteur.setText("Auteur");
        lblAdvertentieUitgeverij.setVisible(true);

    }//GEN-LAST:event_btnSelectBabyActionPerformed

    private void btnEditPersoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPersoonActionPerformed
        
        if (selectPersoon != null) {
            selectPersoon.setAanspreekTitel(txtTitel.getText());
            selectPersoon.setVoornaam(txtVoornaam.getText());
            selectPersoon.setFamilienaam(txtFamilieNaam.getText());
            selectPersoon.setEmail(txtEmail.getText());
            selectPersoon.setWoonPlaats(txtWoonplaats.getText());
            selectPersoon.setUserName(txtUserName.getText());
            selectPersoon.setPassWord(txtPassWord.getText());
            PersoonService.UpdatePersoon(selectPersoon.getId(), selectPersoon);
        }
        ListboxOpvullen();
    }//GEN-LAST:event_btnEditPersoonActionPerformed

    private void btnAddPersoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersoonActionPerformed
        
        if (selectPersoon != null) {
            JOptionPane.showMessageDialog(this, "Deze gebruiker bestaat al indien, u een nieuw gebruiker wil toevoegen kies dan voor de Add knop nadat u alle velden heeft leeg gemaakt met de Clear knop");
        } else {
            
            Persoon p = new Persoon();
            p.setAanspreekTitel(txtTitel.getText());
            p.setVoornaam(txtVoornaam.getText());
            p.setFamilienaam(txtFamilieNaam.getText());
            p.setEmail(txtEmail.getText());
            p.setWoonPlaats(txtWoonplaats.getText());
            p.setUserName(txtUserName.getText());
            p.setPassWord(txtPassWord.getText());
            
            PersoonService.PersoonAdd(p);
        }
        ListboxOpvullen();
        ClearPersoon();
    }//GEN-LAST:event_btnAddPersoonActionPerformed

    private void btnClearPersoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPersoonActionPerformed
        ClearPersoon();

    }//GEN-LAST:event_btnClearPersoonActionPerformed

    private void btnDeleteKlerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteKlerenActionPerformed
        
        Kleren kleren = new Kleren();
        kleren = (Kleren) lstKleren.getSelectedValue();
        
        if (kleren != null) {
            Kleren Kleren = kleren;
            KlerenService.KlerenDelete(kleren);
            
        }
        KlerenListOpvullen();

    }//GEN-LAST:event_btnDeleteKlerenActionPerformed

    private void btnAddGebruiker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGebruiker2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddGebruiker2ActionPerformed

    private void btnSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFileActionPerformed
        JFileChooser dialog = new JFileChooser();
        dialog.showOpenDialog(this);
        String file = dialog.getSelectedFile().getAbsolutePath();
        
        BufferedReader in;
        ArrayList<String> regels = new ArrayList<>();
        String regel;
        try {
            in = new BufferedReader(new FileReader(file));
            regel = in.readLine();
            
            while (regel != null) {
                regels.add(regel);
                regel = in.readLine();
            }
            
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Fout bij lezen bestand");
        }

        //txtLijnen.setText("" + regels.size());
    }//GEN-LAST:event_btnSelectFileActionPerformed

    private void cbxGeslachtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGeslachtActionPerformed

    }//GEN-LAST:event_cbxGeslachtActionPerformed

    private void btnSelectSpeelgoedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectSpeelgoedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectSpeelgoedActionPerformed

    private void btnSelectBoekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectBoekActionPerformed
        
        cbxGeslacht.setVisible(false);
        lblGeslacht.setVisible(false);
        selectBoek = (Boeken) lstBoeken.getSelectedValue();
        if (selectBoek.getBoekenFoto() != null) {
            byte[] imageBytes;
            byte[] image = selectBoek.getBoekenFoto();
            ImageIcon icon = new ImageIcon(image);
            btnFoto.setIcon(icon);
        }
        if (selectBoek != null) {
            
            Boeken boek = selectBoek;
            txtAdvertentieTitel.setText(selectBoek.getTitel());
            txtAdvertentieUitgeverij.setText(selectBoek.getTitel());
            txtOmschrijving.setText(selectBoek.getOmschrijving());
            txtAdvertentieAuteur.setText(selectBoek.getAuteur());
            txtAdvertentieUitgeverij.setText(selectBoek.getUitgeverij());
            txtAdvertentieCategorie.setText(selectBoek.getCategorie());
            
        }
        cbxGeslacht.setVisible(true);
        lblGeslacht.setVisible(true);
    }//GEN-LAST:event_btnSelectBoekActionPerformed

    private void btnSelectKlerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectKlerenActionPerformed
        
        selectBoek = (Boeken) lstBoeken.getSelectedValue();
        
        if (selectBoek != null) {
            byte[] imageBytes;
            byte[] image = selectBoek.getBoekenFoto();
            ImageIcon icon = new ImageIcon(image);
            Boeken boek = selectBoek;
            txtAdvertentieTitel.setText(selectBoek.getTitel());
            txtAdvertentieUitgeverij.setText(selectBoek.getTitel());
            txtOmschrijving.setText(selectBoek.getOmschrijving());
            txtAdvertentieAuteur.setText(selectBoek.getAuteur());
            txtAdvertentieUitgeverij.setText(selectBoek.getUitgeverij());
            txtAdvertentieCategorie.setText(selectBoek.getCategorie());
            
            btnFoto.setIcon(icon);
    }//GEN-LAST:event_btnSelectKlerenActionPerformed
    }
    private void btnSelectPeroonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectPeroonActionPerformed
        selectPersoon = (Persoon) lstPersonen.getSelectedValue();
        
        if (selectPersoon != null) {
            Persoon Persoon = selectPersoon;
            txtTitel.setText(selectPersoon.getAanspreekTitel());
            txtVoornaam.setText(selectPersoon.getVoornaam());
            txtFamilieNaam.setText(selectPersoon.getFamilienaam());
            txtEmail.setText(selectPersoon.getEmail());
            txtWoonplaats.setText(selectPersoon.getWoonPlaats());
            txtUserName.setText(selectPersoon.getUserName());
            txtPassWord.setText(selectPersoon.getPassWord());
            
        }
        BoekListOpvullen();
        BabyListOpvullen();
        KlerenListOpvullen();
        SpeelgoedListOpvullen();
    }//GEN-LAST:event_btnSelectPeroonActionPerformed

    private void btnVerwijderFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerwijderFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerwijderFotoActionPerformed

    private void btnDeletePersoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePersoonActionPerformed
        Persoon persoon = new Persoon();
        persoon = (Persoon) lstPersonen.getSelectedValue();
        
        if (persoon != null) {
            Persoon Persoon = persoon;
            PersoonService.PersoonDelete(persoon);
            
        }
    }//GEN-LAST:event_btnDeletePersoonActionPerformed

    private void btnDeleteBoekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBoekActionPerformed
        Boeken boek = new Boeken();
        boek = (Boeken) lstBoeken.getSelectedValue();
        
        if (boek != null) {
            Boeken Boeken = boek;
            BoekService.BoekDelete(boek);
            
        }
        BoekListOpvullen();
    }//GEN-LAST:event_btnDeleteBoekActionPerformed

    private void btnDeleteBabyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBabyActionPerformed
        Babyspullen baby = new Babyspullen();
        baby = (Babyspullen) lstBabySpullen.getSelectedValue();
        
        if (baby != null) {
            Babyspullen Babyspullen = baby;
            BabyService.BabyDelete(baby);
            
        }
        BabyListOpvullen();
    }//GEN-LAST:event_btnDeleteBabyActionPerformed

    private void btnDeleteSpeelgoedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSpeelgoedActionPerformed
        Speelgoed speel = new Speelgoed();
        speel = (Speelgoed) lstSpeelgoed.getSelectedValue();
        
        if (speel != null) {
            Speelgoed Speel = speel;
            SpeelgoedService.SpeelgoedDelete(speel);
            
        }
        SpeelgoedListOpvullen();
    }//GEN-LAST:event_btnDeleteSpeelgoedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeheerderUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeheerderUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeheerderUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeheerderUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeheerderUI1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGebruiker2;
    private javax.swing.JButton btnAddPersoon;
    private javax.swing.JButton btnClearPersoon;
    private javax.swing.JButton btnDelete2;
    private javax.swing.JButton btnDeleteBaby;
    private javax.swing.JButton btnDeleteBoek1;
    private javax.swing.JButton btnDeleteKleren;
    private javax.swing.JButton btnDeletePersoon;
    private javax.swing.JButton btnDeleteSpeelgoed;
    private javax.swing.JButton btnEditPersoon;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnSelectBaby;
    private javax.swing.JButton btnSelectBoek;
    private javax.swing.JButton btnSelectFile;
    private javax.swing.JButton btnSelectKleren;
    private javax.swing.JButton btnSelectPeroon;
    private javax.swing.JButton btnSelectSpeelgoed;
    private javax.swing.JButton btnVerwijderFoto;
    private javax.swing.JComboBox cbxGeslacht;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblAanspreekTitel1;
    private javax.swing.JLabel lblAanspreekTitel2;
    private javax.swing.JLabel lblAanspreekTitel3;
    private javax.swing.JLabel lblAanspreekTitel4;
    private javax.swing.JLabel lblAanspreekTitel5;
    private javax.swing.JLabel lblAdvertentieAuteur2;
    private javax.swing.JLabel lblAdvertentieCategorie;
    private javax.swing.JLabel lblAdvertentieUitgeverij;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblFamilieNaam;
    private javax.swing.JLabel lblFamilieNaam2;
    private javax.swing.JLabel lblGeslacht;
    private javax.swing.JLabel lblPassWord;
    private javax.swing.JLabel lblPassWord2;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserName2;
    private javax.swing.JLabel lblVoornaam;
    private javax.swing.JLabel lblVoornaam2;
    private javax.swing.JLabel lblWoonplaats;
    private javax.swing.JLabel lblWoonplaats2;
    private javax.swing.JList lstBabySpullen;
    private javax.swing.JList lstBoeken;
    private javax.swing.JList lstKleren;
    private javax.swing.JList lstPersonen;
    private javax.swing.JList lstSpeelgoed;
    private javax.swing.JTextField txtAanspreekTitel2;
    private javax.swing.JTextField txtAdvertentieAuteur;
    private javax.swing.JTextField txtAdvertentieCategorie;
    private javax.swing.JTextField txtAdvertentieTitel;
    private javax.swing.JTextField txtAdvertentieUitgeverij;
    private javax.swing.JButton txtEditGebruiker3;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtFamilieNaam;
    private javax.swing.JTextField txtFamilieNaam2;
    private javax.swing.JTextArea txtOmschrijving;
    private javax.swing.JTextField txtPassWord;
    private javax.swing.JTextField txtPassWord2;
    private javax.swing.JTextField txtTitel;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserName2;
    private javax.swing.JTextField txtVoornaam;
    private javax.swing.JTextField txtVoornaam2;
    private javax.swing.JTextField txtWoonplaats;
    private javax.swing.JTextField txtWoonplaats2;
    // End of variables declaration//GEN-END:variables
}
