/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BO.Persoon;
import Services.BabyService;
import Services.BoekService;
import Services.KlerenService;
import Services.PersoonService;
import Services.SpeelgoedService;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;

/**
 *
 * @author Tom
 */
public class BeheerderUI1 extends javax.swing.JFrame {

    /**
     * Creates new form BeheerderUI1
     */
    public BeheerderUI1() {
        initComponents();
        ListboxOpvullen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Persoon selectPersoon = new Persoon();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelete2 = new javax.swing.JButton();
        btnAddGebruiker2 = new javax.swing.JButton();
        lblEmail2 = new javax.swing.JLabel();
        txtUserName2 = new javax.swing.JTextField();
        lblVoornaam2 = new javax.swing.JLabel();
        txtFamilieNaam2 = new javax.swing.JTextField();
        txtWoonplaats2 = new javax.swing.JTextField();
        lblUserName2 = new javax.swing.JLabel();
        lblAanspreekTitel2 = new javax.swing.JLabel();
        lblPassWord2 = new javax.swing.JLabel();
        txtEmail2 = new javax.swing.JTextField();
        lblFamilieNaam2 = new javax.swing.JLabel();
        lblWoonplaats2 = new javax.swing.JLabel();
        txtEditGebruiker3 = new javax.swing.JButton();
        txtPassWord2 = new javax.swing.JTextField();
        txtAanspreekTitel2 = new javax.swing.JTextField();
        txtVoornaam2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPersonen = new javax.swing.JList();
        btnSelectBaby = new javax.swing.JButton();
        lblAanspreekTitel = new javax.swing.JLabel();
        txtTitel = new javax.swing.JTextField();
        lblVoornaam = new javax.swing.JLabel();
        txtVoornaam = new javax.swing.JTextField();
        lblFamilieNaam = new javax.swing.JLabel();
        txtFamilieNaam = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblWoonplaats = new javax.swing.JLabel();
        txtWoonplaats = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassWord = new javax.swing.JLabel();
        txtPassWord = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnEditGebruiker = new javax.swing.JButton();
        btnAddGebruiker = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstBoeken = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstBabySpullen = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstKleren = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstSpeelgoed = new javax.swing.JList();
        lblAanspreekTitel1 = new javax.swing.JLabel();
        txtTitelAdvertentie = new javax.swing.JTextField();
        lblAanspreekTitel3 = new javax.swing.JLabel();
        panFoto = new javax.swing.JPanel();
        lblAanspreekTitel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOmschrijving = new javax.swing.JTextArea();
        SelectFile = new javax.swing.JButton();
        lblAanspreekTitel5 = new javax.swing.JLabel();
        cbxGeslacht = new javax.swing.JComboBox();
        btnSelectPeroon = new javax.swing.JButton();
        btnSelectSpeelgoed = new javax.swing.JButton();
        btnSelectBoek = new javax.swing.JButton();
        btnSelectKleren = new javax.swing.JButton();

        btnDelete2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelete2.setText("Delete");
        btnDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete2ActionPerformed(evt);
            }
        });

        btnAddGebruiker2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddGebruiker2.setText("Add");
        btnAddGebruiker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGebruiker2ActionPerformed(evt);
            }
        });

        lblEmail2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail2.setText("E-mail:");

        txtUserName2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblVoornaam2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVoornaam2.setText("Voornaam:");

        txtFamilieNaam2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtWoonplaats2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblUserName2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserName2.setText("Gebruiker naam:");

        lblAanspreekTitel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAanspreekTitel2.setText("Aanspreek Titel:");

        lblPassWord2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassWord2.setText("Wachtwoord:");

        txtEmail2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblFamilieNaam2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFamilieNaam2.setText("Familienaam");

        lblWoonplaats2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblWoonplaats2.setText("WoonPlaats:");

        txtEditGebruiker3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEditGebruiker3.setText("Edit");
        txtEditGebruiker3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditGebruiker3ActionPerformed(evt);
            }
        });

        txtPassWord2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtAanspreekTitel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtVoornaam2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beheerder");
        setMinimumSize(new java.awt.Dimension(1620, 920));
        getContentPane().setLayout(null);

        lstPersonen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(lstPersonen);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(37, 103, 251, 320);

        btnSelectBaby.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectBaby.setText("Select");
        btnSelectBaby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectBabyActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectBaby);
        btnSelectBaby.setBounds(730, 440, 79, 31);

        lblAanspreekTitel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAanspreekTitel.setText("Geslacht:");
        getContentPane().add(lblAanspreekTitel);
        lblAanspreekTitel.setBounds(810, 730, 100, 22);

        txtTitel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtTitel);
        txtTitel.setBounds(180, 510, 190, 28);

        lblVoornaam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVoornaam.setText("Voornaam:");
        getContentPane().add(lblVoornaam);
        lblVoornaam.setBounds(30, 560, 86, 22);

        txtVoornaam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtVoornaam);
        txtVoornaam.setBounds(180, 560, 190, 28);

        lblFamilieNaam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFamilieNaam.setText("Familienaam");
        getContentPane().add(lblFamilieNaam);
        lblFamilieNaam.setBounds(30, 610, 97, 22);

        txtFamilieNaam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtFamilieNaam);
        txtFamilieNaam.setBounds(180, 600, 190, 28);

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setText("E-mail:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(30, 660, 55, 22);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtEmail);
        txtEmail.setBounds(180, 650, 190, 28);

        lblWoonplaats.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblWoonplaats.setText("WoonPlaats:");
        getContentPane().add(lblWoonplaats);
        lblWoonplaats.setBounds(30, 700, 98, 22);

        txtWoonplaats.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtWoonplaats);
        txtWoonplaats.setBounds(180, 700, 190, 28);

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserName.setText("Gebruiker naam:");
        getContentPane().add(lblUserName);
        lblUserName.setBounds(30, 750, 130, 22);

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtUserName);
        txtUserName.setBounds(180, 740, 190, 28);

        lblPassWord.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassWord.setText("Wachtwoord:");
        getContentPane().add(lblPassWord);
        lblPassWord.setBounds(30, 790, 104, 22);

        txtPassWord.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtPassWord);
        txtPassWord.setBounds(180, 790, 190, 28);

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(30, 840, 90, 31);

        btnEditGebruiker.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditGebruiker.setText("Edit");
        btnEditGebruiker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditGebruikerActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditGebruiker);
        btnEditGebruiker.setBounds(140, 840, 107, 31);

        btnAddGebruiker.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddGebruiker.setText("Verwijder foto");
        btnAddGebruiker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGebruikerActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddGebruiker);
        btnAddGebruiker.setBounds(490, 830, 220, 31);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Gebruikers Lijst");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(48, 40, 179, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Babyspullen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 30, 220, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Boeken");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 30, 90, 60);

        lstBoeken.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane4.setViewportView(lstBoeken);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(310, 110, 290, 320);

        lstBabySpullen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane5.setViewportView(lstBabySpullen);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(630, 110, 290, 320);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Kleren");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(960, 30, 220, 60);

        lstKleren.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane6.setViewportView(lstKleren);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(960, 110, 290, 320);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Speelgoed");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1290, 30, 220, 60);

        lstSpeelgoed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane7.setViewportView(lstSpeelgoed);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(1290, 110, 290, 320);

        lblAanspreekTitel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAanspreekTitel1.setText("Aanspreek Titel:");
        getContentPane().add(lblAanspreekTitel1);
        lblAanspreekTitel1.setBounds(30, 510, 127, 22);

        txtTitelAdvertentie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtTitelAdvertentie);
        txtTitelAdvertentie.setBounds(500, 500, 190, 28);

        lblAanspreekTitel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAanspreekTitel3.setText("Titel:");
        getContentPane().add(lblAanspreekTitel3);
        lblAanspreekTitel3.setBounds(440, 510, 50, 22);

        panFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panFoto.setLayout(new javax.swing.BoxLayout(panFoto, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(panFoto);
        panFoto.setBounds(500, 570, 190, 190);

        lblAanspreekTitel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAanspreekTitel4.setText("Foto:");
        getContentPane().add(lblAanspreekTitel4);
        lblAanspreekTitel4.setBounds(440, 570, 50, 22);

        txtOmschrijving.setColumns(20);
        txtOmschrijving.setRows(5);
        jScrollPane2.setViewportView(txtOmschrijving);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(930, 510, 320, 160);

        SelectFile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SelectFile.setText("Kies een andere foto");
        SelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectFileActionPerformed(evt);
            }
        });
        getContentPane().add(SelectFile);
        SelectFile.setBounds(490, 780, 220, 30);

        lblAanspreekTitel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAanspreekTitel5.setText("Omschrijving:");
        getContentPane().add(lblAanspreekTitel5);
        lblAanspreekTitel5.setBounds(800, 510, 130, 22);

        cbxGeslacht.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxGeslacht.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jongen", "Meisje" }));
        cbxGeslacht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGeslachtActionPerformed(evt);
            }
        });
        getContentPane().add(cbxGeslacht);
        cbxGeslacht.setBounds(940, 722, 120, 30);

        btnSelectPeroon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectPeroon.setText("Select");
        btnSelectPeroon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectPeroonActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectPeroon);
        btnSelectPeroon.setBounds(120, 440, 79, 31);

        btnSelectSpeelgoed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectSpeelgoed.setText("Select");
        btnSelectSpeelgoed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectSpeelgoedActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectSpeelgoed);
        btnSelectSpeelgoed.setBounds(1400, 440, 79, 31);

        btnSelectBoek.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectBoek.setText("Select");
        btnSelectBoek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectBoekActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectBoek);
        btnSelectBoek.setBounds(410, 440, 79, 31);

        btnSelectKleren.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectKleren.setText("Select");
        btnSelectKleren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectKlerenActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectKleren);
        btnSelectKleren.setBounds(1080, 440, 79, 31);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void ListboxOpvullen() {
        PersoonService p = new PersoonService();
        lstPersonen.setListData(p.AllePersonenOphalen().toArray());
    }

    private void BoekListOpvullen() {
        BoekService b = new BoekService();
        lstBoeken.setListData(b.SelecteerBoek(selectPersoon.getId()).toArray());

    }

    private void BabyListOpvullen() {
        BabyService ba = new BabyService();
        if (selectPersoon != null) {
            lstBabySpullen.setListData(ba.SelecteerBaby(selectPersoon.getId()).toArray());
        }

    }

    private void KlerenListOpvullen() {
        KlerenService k = new KlerenService();
        lstKleren.setListData(k.SelecteerKleren(selectPersoon.getId()).toArray());

    }

    private void SpeelgoedListOpvullen() {
        SpeelgoedService sp = new SpeelgoedService();
        lstSpeelgoed.setListData(sp.SelecteerSpeelgoed(selectPersoon.getId()).toArray());

    }
    private void btnSelectBabyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectBabyActionPerformed

        
    }//GEN-LAST:event_btnSelectBabyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Persoon persoon = new Persoon();
        persoon = (Persoon) lstPersonen.getSelectedValue();

        if (persoon != null) {
            Persoon Persoon = persoon;
            PersoonService.PersoonDelete(persoon);

        }
        ListboxOpvullen();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditGebruikerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditGebruikerActionPerformed
        if (selectPersoon != null) {
            PersoonService.PersoonUpdate(selectPersoon.getId());
        }
        ListboxOpvullen();
    }//GEN-LAST:event_btnEditGebruikerActionPerformed

    private void btnAddGebruikerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGebruikerActionPerformed
        Persoon p = new Persoon();
        p.setAanspreekTitel(txtTitel.getText());
        p.setVoornaam(txtVoornaam.getText());
        p.setFamilienaam(txtFamilieNaam.getText());
        p.setEmail(txtEmail.getText());
        p.setWoonPlaats(txtWoonplaats.getText());
        p.setUserName(txtUserName.getText());
        p.setPassWord(txtPassWord.getText());

        PersoonService.PersoonAdd(p);
        ListboxOpvullen();
    }//GEN-LAST:event_btnAddGebruikerActionPerformed

    private void btnDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete2ActionPerformed

    private void txtEditGebruiker3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditGebruiker3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditGebruiker3ActionPerformed

    private void btnAddGebruiker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGebruiker2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddGebruiker2ActionPerformed

    private void SelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectFileActionPerformed
        JFileChooser dialog = new JFileChooser();
        dialog.showOpenDialog(this);
        String file = dialog.getSelectedFile().getAbsolutePath();

        BufferedReader in;
        ArrayList<String> regels = new ArrayList<>();
        String regel;
        try {
            in = new BufferedReader(new FileReader(file));
            regel = in.readLine();

            while (regel != null) {
                regels.add(regel);
                regel = in.readLine();
            }

        } catch (FileNotFoundException ex) {
            System.out.println(ex.getMessage());
        } catch (IOException ex) {
            System.out.println("Fout bij lezen bestand");
        }

        //txtLijnen.setText("" + regels.size());
    }//GEN-LAST:event_SelectFileActionPerformed

    private void cbxGeslachtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGeslachtActionPerformed

    }//GEN-LAST:event_cbxGeslachtActionPerformed

    private void btnSelectSpeelgoedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectSpeelgoedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectSpeelgoedActionPerformed

    private void btnSelectBoekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectBoekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectBoekActionPerformed

    private void btnSelectKlerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectKlerenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectKlerenActionPerformed

    private void btnSelectPeroonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectPeroonActionPerformed
       selectPersoon = (Persoon) lstPersonen.getSelectedValue();

        if (selectPersoon != null) {
            Persoon Persoon = selectPersoon;
            txtTitel.setText(selectPersoon.getAanspreekTitel());
            txtVoornaam.setText(selectPersoon.getVoornaam());
            txtFamilieNaam.setText(selectPersoon.getFamilienaam());
            txtEmail.setText(selectPersoon.getEmail());
            txtWoonplaats.setText(selectPersoon.getWoonPlaats());
            txtUserName.setText(selectPersoon.getUserName());
            txtPassWord.setText(selectPersoon.getPassWord());

        }
        BoekListOpvullen();
        BabyListOpvullen();
        KlerenListOpvullen();
        SpeelgoedListOpvullen();
    }//GEN-LAST:event_btnSelectPeroonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeheerderUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeheerderUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeheerderUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeheerderUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeheerderUI1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SelectFile;
    private javax.swing.JButton btnAddGebruiker;
    private javax.swing.JButton btnAddGebruiker2;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete2;
    private javax.swing.JButton btnEditGebruiker;
    private javax.swing.JButton btnSelectBaby;
    private javax.swing.JButton btnSelectBoek;
    private javax.swing.JButton btnSelectKleren;
    private javax.swing.JButton btnSelectPeroon;
    private javax.swing.JButton btnSelectSpeelgoed;
    private javax.swing.JComboBox cbxGeslacht;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblAanspreekTitel;
    private javax.swing.JLabel lblAanspreekTitel1;
    private javax.swing.JLabel lblAanspreekTitel2;
    private javax.swing.JLabel lblAanspreekTitel3;
    private javax.swing.JLabel lblAanspreekTitel4;
    private javax.swing.JLabel lblAanspreekTitel5;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblFamilieNaam;
    private javax.swing.JLabel lblFamilieNaam2;
    private javax.swing.JLabel lblPassWord;
    private javax.swing.JLabel lblPassWord2;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserName2;
    private javax.swing.JLabel lblVoornaam;
    private javax.swing.JLabel lblVoornaam2;
    private javax.swing.JLabel lblWoonplaats;
    private javax.swing.JLabel lblWoonplaats2;
    private javax.swing.JList lstBabySpullen;
    private javax.swing.JList lstBoeken;
    private javax.swing.JList lstKleren;
    private javax.swing.JList lstPersonen;
    private javax.swing.JList lstSpeelgoed;
    private javax.swing.JPanel panFoto;
    private javax.swing.JTextField txtAanspreekTitel2;
    private javax.swing.JButton txtEditGebruiker3;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtFamilieNaam;
    private javax.swing.JTextField txtFamilieNaam2;
    private javax.swing.JTextArea txtOmschrijving;
    private javax.swing.JTextField txtPassWord;
    private javax.swing.JTextField txtPassWord2;
    private javax.swing.JTextField txtTitel;
    private javax.swing.JTextField txtTitelAdvertentie;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserName2;
    private javax.swing.JTextField txtVoornaam;
    private javax.swing.JTextField txtVoornaam2;
    private javax.swing.JTextField txtWoonplaats;
    private javax.swing.JTextField txtWoonplaats2;
    // End of variables declaration//GEN-END:variables
}
