/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BO.Babyspullen;
import BO.Boeken;
import BO.Kleren;
import BO.Persoon;
import BO.Speelgoed;
import Services.BabyService;
import Services.BoekService;
import Services.KlerenService;
import Services.PersoonService;
import Services.SpeelgoedService;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Tom
 */
public class BeheerderUI1 extends javax.swing.JFrame {

    /**
     * Creates new form BeheerderUI1
     */
    public BeheerderUI1() {
        initComponents();
        ListboxOpvullen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelete2 = new javax.swing.JButton();
        btnAddGebruiker2 = new javax.swing.JButton();
        lblEmail2 = new javax.swing.JLabel();
        txtUserName2 = new javax.swing.JTextField();
        lblVoornaam2 = new javax.swing.JLabel();
        txtFamilieNaam2 = new javax.swing.JTextField();
        txtWoonplaats2 = new javax.swing.JTextField();
        lblUserName2 = new javax.swing.JLabel();
        lblAanspreekTitel2 = new javax.swing.JLabel();
        lblPassWord2 = new javax.swing.JLabel();
        txtEmail2 = new javax.swing.JTextField();
        lblFamilieNaam2 = new javax.swing.JLabel();
        lblWoonplaats2 = new javax.swing.JLabel();
        txtEditGebruiker3 = new javax.swing.JButton();
        txtPassWord2 = new javax.swing.JTextField();
        txtAanspreekTitel2 = new javax.swing.JTextField();
        txtVoornaam2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPersonen = new javax.swing.JList();
        btnSelectBaby = new javax.swing.JButton();
        lblAdvertentieUitgeverij = new javax.swing.JLabel();
        txtTitel = new javax.swing.JTextField();
        lblVoornaam = new javax.swing.JLabel();
        txtVoornaam = new javax.swing.JTextField();
        lblFamilieNaam = new javax.swing.JLabel();
        txtFamilieNaam = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblWoonplaats = new javax.swing.JLabel();
        txtWoonplaats = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassWord = new javax.swing.JLabel();
        txtPassWord = new javax.swing.JTextField();
        btnDeleteKleren = new javax.swing.JButton();
        btnEditPersoon = new javax.swing.JButton();
        btnAddPersoon = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstBoeken = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstBabySpullen = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstKleren = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstSpeelgoed = new javax.swing.JList();
        lblAanspreekTitel1 = new javax.swing.JLabel();
        txtAdvertentieUitgeverij = new javax.swing.JTextField();
        lblTitel = new javax.swing.JLabel();
        lblAanspreekTitel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOmschrijving = new javax.swing.JTextArea();
        btnSelectFile = new javax.swing.JButton();
        lblAanspreekTitel5 = new javax.swing.JLabel();
        cbxGeslacht = new javax.swing.JComboBox();
        btnSelectPeroon = new javax.swing.JButton();
        btnSelectSpeelgoed = new javax.swing.JButton();
        btnSelectBoek = new javax.swing.JButton();
        btnSelectKleren = new javax.swing.JButton();
        btnVerwijderFoto = new javax.swing.JButton();
        btnClearPersoon = new javax.swing.JButton();
        lblGeslacht = new javax.swing.JLabel();
        txtAdvertentieTitel = new javax.swing.JTextField();
        lblAdvertentieCategorie = new javax.swing.JLabel();
        lblAdvertentieAuteur = new javax.swing.JLabel();
        txtAdvertentieAuteur = new javax.swing.JTextField();
        btnFoto = new javax.swing.JButton();
        btnDeletePersoon = new javax.swing.JButton();
        btnDeleteBoek1 = new javax.swing.JButton();
        btnDeleteSpeelgoed = new javax.swing.JButton();
        btnDeleteBaby = new javax.swing.JButton();
        cbxCategorie = new javax.swing.JComboBox();
        btnEditBaby = new javax.swing.JButton();
        btnEditBoek1 = new javax.swing.JButton();
        btnEditKleren = new javax.swing.JButton();
        btnEditSpeelgoed = new javax.swing.JButton();
        lblAchtergrond = new javax.swing.JLabel();

        btnDelete2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelete2.setText("Delete");
        btnDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPersoonActionPerformed(evt);
            }
        });

        btnAddGebruiker2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddGebruiker2.setText("Add");
        btnAddGebruiker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGebruiker2ActionPerformed(evt);
            }
        });

        lblEmail2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail2.setText("E-mail:");

        txtUserName2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblVoornaam2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVoornaam2.setText("Voornaam:");

        txtFamilieNaam2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtWoonplaats2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblUserName2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserName2.setText("Gebruiker naam:");

        lblAanspreekTitel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAanspreekTitel2.setText("Aanspreek Titel:");

        lblPassWord2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassWord2.setText("Wachtwoord:");

        txtEmail2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblFamilieNaam2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFamilieNaam2.setText("Familienaam");

        lblWoonplaats2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblWoonplaats2.setText("WoonPlaats:");

        txtEditGebruiker3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEditGebruiker3.setText("Edit");
        txtEditGebruiker3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteKlerenActionPerformed(evt);
            }
        });

        txtPassWord2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtAanspreekTitel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtVoornaam2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beheerder");
        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(1500, 850));
        getContentPane().setLayout(null);

        lstPersonen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(lstPersonen);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 251, 310);

        btnSelectBaby.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectBaby.setText("Select");
        btnSelectBaby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectBabyActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectBaby);
        btnSelectBaby.setBounds(590, 380, 79, 31);

        lblAdvertentieUitgeverij.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAdvertentieUitgeverij.setText("Uitgeverij:");
        getContentPane().add(lblAdvertentieUitgeverij);
        lblAdvertentieUitgeverij.setBounds(460, 590, 100, 30);

        txtTitel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtTitel);
        txtTitel.setBounds(150, 440, 210, 28);

        lblVoornaam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVoornaam.setText("Voornaam:");
        getContentPane().add(lblVoornaam);
        lblVoornaam.setBounds(10, 480, 86, 22);

        txtVoornaam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtVoornaam);
        txtVoornaam.setBounds(150, 480, 210, 28);

        lblFamilieNaam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFamilieNaam.setText("Familienaam:");
        getContentPane().add(lblFamilieNaam);
        lblFamilieNaam.setBounds(10, 520, 103, 22);

        txtFamilieNaam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtFamilieNaam);
        txtFamilieNaam.setBounds(150, 520, 210, 28);

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setText("E-mail:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(10, 560, 55, 22);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtEmail);
        txtEmail.setBounds(150, 560, 210, 28);

        lblWoonplaats.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblWoonplaats.setText("WoonPlaats:");
        getContentPane().add(lblWoonplaats);
        lblWoonplaats.setBounds(10, 600, 98, 22);

        txtWoonplaats.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtWoonplaats);
        txtWoonplaats.setBounds(150, 600, 210, 28);

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserName.setText("Gebruikersnaam:");
        getContentPane().add(lblUserName);
        lblUserName.setBounds(10, 640, 140, 22);

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtUserName);
        txtUserName.setBounds(150, 640, 210, 28);

        lblPassWord.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassWord.setText("Wachtwoord:");
        getContentPane().add(lblPassWord);
        lblPassWord.setBounds(10, 680, 104, 22);

        txtPassWord.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtPassWord);
        txtPassWord.setBounds(150, 680, 210, 28);

        btnDeleteKleren.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeleteKleren.setText("Delete");
        btnDeleteKleren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteKlerenActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteKleren);
        btnDeleteKleren.setBounds(980, 380, 90, 31);

        btnEditPersoon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditPersoon.setText("Edit");
        btnEditPersoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPersoonActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditPersoon);
        btnEditPersoon.setBounds(10, 720, 107, 31);

        btnAddPersoon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddPersoon.setText("Add");
        btnAddPersoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersoonActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddPersoon);
        btnAddPersoon.setBounds(130, 720, 100, 31);

        lblBackground.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblBackground.setText("Gebruikers Lijst");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(10, 20, 179, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Babyspullen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(580, 10, 220, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Boeken");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 10, 90, 60);

        lstBoeken.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane4.setViewportView(lstBoeken);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(280, 60, 290, 310);

        lstBabySpullen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane5.setViewportView(lstBabySpullen);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(580, 60, 290, 310);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Kleren");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(880, 20, 150, 50);

        lstKleren.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane6.setViewportView(lstKleren);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(880, 60, 290, 310);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Speelgoed");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1180, 20, 140, 50);

        lstSpeelgoed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane7.setViewportView(lstSpeelgoed);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(1180, 60, 290, 310);

        lblAanspreekTitel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAanspreekTitel1.setText("Aanspreek Titel:");
        getContentPane().add(lblAanspreekTitel1);
        lblAanspreekTitel1.setBounds(10, 440, 127, 22);

        txtAdvertentieUitgeverij.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtAdvertentieUitgeverij);
        txtAdvertentieUitgeverij.setBounds(550, 590, 210, 30);

        lblTitel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitel.setText("Titel:");
        getContentPane().add(lblTitel);
        lblTitel.setBounds(460, 470, 50, 30);

        lblAanspreekTitel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAanspreekTitel4.setText("Foto:");
        getContentPane().add(lblAanspreekTitel4);
        lblAanspreekTitel4.setBounds(1220, 440, 50, 22);

        txtOmschrijving.setColumns(20);
        txtOmschrijving.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtOmschrijving.setLineWrap(true);
        txtOmschrijving.setRows(5);
        jScrollPane2.setViewportView(txtOmschrijving);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(830, 500, 290, 190);

        btnSelectFile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectFile.setText("Kies een andere foto");
        btnSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFileActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectFile);
        btnSelectFile.setBounds(1230, 680, 220, 30);

        lblAanspreekTitel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAanspreekTitel5.setText("Omschrijving:");
        getContentPane().add(lblAanspreekTitel5);
        lblAanspreekTitel5.setBounds(830, 470, 130, 22);

        cbxGeslacht.setEditable(true);
        cbxGeslacht.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxGeslacht.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jongen", "Meisje" }));
        cbxGeslacht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGeslachtActionPerformed(evt);
            }
        });
        getContentPane().add(cbxGeslacht);
        cbxGeslacht.setBounds(550, 640, 210, 30);

        btnSelectPeroon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectPeroon.setText("Select");
        btnSelectPeroon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectPeroonActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectPeroon);
        btnSelectPeroon.setBounds(40, 380, 79, 31);

        btnSelectSpeelgoed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectSpeelgoed.setText("Select");
        btnSelectSpeelgoed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectSpeelgoedActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectSpeelgoed);
        btnSelectSpeelgoed.setBounds(1180, 380, 79, 31);

        btnSelectBoek.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectBoek.setText("Select");
        btnSelectBoek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectBoekActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectBoek);
        btnSelectBoek.setBounds(290, 380, 79, 31);

        btnSelectKleren.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelectKleren.setText("Select");
        btnSelectKleren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectKlerenActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectKleren);
        btnSelectKleren.setBounds(890, 380, 79, 31);

        btnVerwijderFoto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVerwijderFoto.setText("Verwijder foto");
        btnVerwijderFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerwijderFotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerwijderFoto);
        btnVerwijderFoto.setBounds(1230, 720, 220, 30);

        btnClearPersoon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnClearPersoon.setText("Clear");
        btnClearPersoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPersoonActionPerformed(evt);
            }
        });
        getContentPane().add(btnClearPersoon);
        btnClearPersoon.setBounds(240, 720, 107, 31);

        lblGeslacht.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGeslacht.setText("Geslacht:");
        getContentPane().add(lblGeslacht);
        lblGeslacht.setBounds(460, 640, 100, 30);

        txtAdvertentieTitel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtAdvertentieTitel);
        txtAdvertentieTitel.setBounds(550, 470, 210, 30);

        lblAdvertentieCategorie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAdvertentieCategorie.setText("Categorie:");
        getContentPane().add(lblAdvertentieCategorie);
        lblAdvertentieCategorie.setBounds(460, 550, 90, 30);

        lblAdvertentieAuteur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAdvertentieAuteur.setText("Auteur:");
        getContentPane().add(lblAdvertentieAuteur);
        lblAdvertentieAuteur.setBounds(460, 510, 100, 30);

        txtAdvertentieAuteur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtAdvertentieAuteur);
        txtAdvertentieAuteur.setBounds(550, 510, 210, 30);

        btnFoto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFoto.setText("Geen afbeelding");
        btnFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnFoto.setFocusable(false);
        btnFoto.setRolloverEnabled(false);
        getContentPane().add(btnFoto);
        btnFoto.setBounds(1220, 470, 220, 200);

        btnDeletePersoon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeletePersoon.setText("Delete");
        btnDeletePersoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePersoonActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletePersoon);
        btnDeletePersoon.setBounds(140, 380, 90, 31);

        btnDeleteBoek1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeleteBoek1.setText("Delete");
        btnDeleteBoek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBoekActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteBoek1);
        btnDeleteBoek1.setBounds(380, 380, 90, 31);

        btnDeleteSpeelgoed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeleteSpeelgoed.setText("Delete");
        btnDeleteSpeelgoed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSpeelgoedActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteSpeelgoed);
        btnDeleteSpeelgoed.setBounds(1270, 380, 90, 31);

        btnDeleteBaby.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeleteBaby.setText("Delete");
        btnDeleteBaby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBabyActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteBaby);
        btnDeleteBaby.setBounds(680, 380, 90, 31);

        cbxCategorie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxCategorie.setMinimumSize(new java.awt.Dimension(169, 28));
        getContentPane().add(cbxCategorie);
        cbxCategorie.setBounds(550, 550, 210, 30);

        btnEditBaby.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditBaby.setText("Edit");
        btnEditBaby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBabyActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditBaby);
        btnEditBaby.setBounds(780, 380, 80, 30);

        btnEditBoek1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditBoek1.setText("Edit");
        btnEditBoek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBoekActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditBoek1);
        btnEditBoek1.setBounds(480, 380, 80, 30);

        btnEditKleren.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditKleren.setText("Edit");
        btnEditKleren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditKlerenActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditKleren);
        btnEditKleren.setBounds(1080, 380, 63, 30);

        btnEditSpeelgoed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditSpeelgoed.setText("Edit");
        btnEditSpeelgoed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSpeelgoedActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditSpeelgoed);
        btnEditSpeelgoed.setBounds(1370, 380, 80, 30);

        lblAchtergrond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/vector1.jpg"))); // NOI18N
        lblAchtergrond.setText("jLabel1");
        getContentPane().add(lblAchtergrond);
        lblAchtergrond.setBounds(0, 0, 1965, 1200);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Persoon selectPersoon = new Persoon();
    Boeken selectBoek = new Boeken();
    Kleren selectKleren = new Kleren();
    Speelgoed selectSpeelgoed = new Speelgoed();
    Babyspullen selectBaby = new Babyspullen();
    PersoonService persoonService = new PersoonService();
    BoekService bookService = new BoekService();
    BabyService babyService = new BabyService();
    KlerenService klerenService = new KlerenService();

    private boolean Geslacht(int geslacht) {
        if (cbxGeslacht.getSelectedIndex() == 0) {
            return true;
        } else {
            return false;
        }
    }

    private void CBXVullen(String select) {
        if ("selectBoek".equals(select)) {
            cbxCategorie.removeAllItems();
            cbxCategorie.addItem("Prenten boeken");
            cbxCategorie.addItem("Voorlees boeken");
            cbxCategorie.addItem("Educatieve boeken");
            cbxCategorie.addItem("Nieuwe ouder");
            if ("PrentenBoeken".equals(selectBoek.getCategorie().toString())) {
                cbxCategorie.setSelectedIndex(0);
            } else if ("VoorleesBoeken".equals(selectBoek.getCategorie().toString())) {
                cbxCategorie.setSelectedIndex(1);
            } else if ("Baby_peuterboekjes".equals(selectBoek.getCategorie().toString())) {
                cbxCategorie.setSelectedIndex(2);
            } else if ("EducatieveBoeken".equals(selectBoek.getCategorie().toString())) {
                cbxCategorie.setSelectedIndex(3);
            } else if ("VoorNieuweOuders".equals(selectBoek.getCategorie().toString())) {
                cbxCategorie.setSelectedIndex(4);
            }

        }
        if ("selectBaby".equals(select)) {
            cbxCategorie.removeAllItems();
            cbxCategorie.addItem("Autostoeltjes");
            cbxCategorie.addItem("Kindermeubelen");
            cbxCategorie.addItem("Kinderwagens");
            cbxCategorie.addItem("Andere");
            if ("Autostoeltjes".equals(selectBaby.getCategorie().toString())) {
                cbxCategorie.setSelectedIndex(0);
            } else if ("Kindermeubelen".equals(selectBaby.getCategorie().toString())) {
                cbxCategorie.setSelectedIndex(1);
            } else if ("Kinderwagens".equals(selectBaby.getCategorie().toString())) {
                cbxCategorie.setSelectedIndex(2);
            } else if ("Andere".equals(selectBaby.getCategorie().toString())) {
                cbxCategorie.setSelectedIndex(3);
            }
        }

        if ("selectKleren".equals(select)) {
            cbxCategorie.removeAllItems();
            cbxCategorie.addItem("Winter");
            cbxCategorie.addItem("Herfst");
            cbxCategorie.addItem("Lente");
            cbxCategorie.addItem("Zomer");
            cbxCategorie.addItem("Alle");
            if ("Winter".equals(selectKleren.getSeizoen().toString())) {
                cbxCategorie.setSelectedIndex(0);
            } else if ("Herfst".equals(selectKleren.getSeizoen().toString())) {
                cbxCategorie.setSelectedIndex(1);
            } else if ("Lente".equals(selectKleren.getSeizoen().toString())) {
                cbxCategorie.setSelectedIndex(2);
            } else if ("Zomer".equals(selectKleren.getSeizoen().toString())) {
                cbxCategorie.setSelectedIndex(3);
            } else if ("Alle".equals(selectKleren.getSeizoen().toString())) {
                cbxCategorie.setSelectedIndex(4);
            }

        }
        if ("selectSpeelgoed".equals(select)) {
            cbxCategorie.removeAllItems();
            cbxCategorie.addItem("Baby");
            cbxCategorie.addItem("Peuter");
            cbxCategorie.addItem("Kleuter");
            cbxCategorie.addItem("Scholier");
            cbxCategorie.addItem("Tiener");
            if ("Baby".equals(selectSpeelgoed.getCategorie().toString())) {
                cbxCategorie.setSelectedIndex(0);
            } else if ("Peuter".equals(selectSpeelgoed.getCategorie().toString())) {
                cbxCategorie.setSelectedIndex(1);
            } else if ("Kleuter".equals(selectSpeelgoed.getCategorie().toString())) {
                cbxCategorie.setSelectedIndex(2);
            } else if ("Scholier".equals(selectSpeelgoed.getCategorie().toString())) {
                cbxCategorie.setSelectedIndex(3);
            } else if ("Tiener".equals(selectSpeelgoed.getCategorie().toString())) {
                cbxCategorie.setSelectedIndex(4);
            }

        }

    }

    private void DetailsVullen(String select) {
        if ("selectBoek".equals(select)) {
            lblAdvertentieAuteur.setText("Auteur");
            lblAdvertentieCategorie.setText("Categorie");
            lblAdvertentieUitgeverij.setText("Uitgeverij");
            lblAdvertentieUitgeverij.setVisible(true);
            txtAdvertentieUitgeverij.setVisible(true);
            lblGeslacht.setVisible(false);
            cbxGeslacht.setVisible(false);
            txtOmschrijving.setText(selectBoek.getOmschrijving());
            // btnFoto.getImageBoek(selectBoek.getId());
            if (selectBoek.getBoekenFoto() != null) {
                byte[] imageBytes;
                byte[] image = selectBoek.getBoekenFoto();
                ImageIcon icon = new ImageIcon(image);
                btnFoto.setIcon(icon);
            } else {
                btnFoto.setIcon(null);
            }
            if (selectBoek != null) {

                Boeken boek = selectBoek;
                txtAdvertentieTitel.setText(selectBoek.getTitel());
                txtAdvertentieAuteur.setText(selectBoek.getAuteur());
                txtAdvertentieUitgeverij.setText(selectBoek.getUitgeverij());

            }

        }
        if ("selectBaby".equals(select)) {
            lblAdvertentieAuteur.setText("Leeftijd");
            lblAdvertentieCategorie.setText("Categorie");
            lblAdvertentieUitgeverij.setVisible(false);
            txtAdvertentieUitgeverij.setVisible(false);
            lblGeslacht.setVisible(true);
            cbxGeslacht.setVisible(true);
            txtOmschrijving.setText(selectBaby.getOmschrijving());
            if (selectBaby.getGeslacht()) {
                cbxGeslacht.setSelectedIndex(0);

            } else {
                cbxGeslacht.setSelectedIndex(1);
            }
            if (selectBaby.getBabyspullenFoto() != null) {
                byte[] imageBytes;
                byte[] image = selectBaby.getBabyspullenFoto();
                ImageIcon icon = new ImageIcon(image);
                btnFoto.setIcon(icon);
            } else {
                btnFoto.setIcon(null);
            }

            if (selectBaby != null) {
                Babyspullen babyspullen = selectBaby;
                txtAdvertentieTitel.setText(selectBaby.getTitel());
                txtAdvertentieAuteur.setText(selectBaby.getLeeftijd().toString());

            }

        }

        if ("selectKleren".equals(select)) {
            lblAdvertentieAuteur.setText("Maat");
            lblAdvertentieCategorie.setText("Seizoen");
            lblAdvertentieUitgeverij.setVisible(false);
            txtAdvertentieUitgeverij.setVisible(false);
            lblGeslacht.setVisible(true);
            cbxGeslacht.setVisible(true);
            txtOmschrijving.setText(selectKleren.getOmschrijving());
            if (selectKleren.getGeslacht()) {
                cbxGeslacht.setSelectedIndex(0);

            } else {
                cbxGeslacht.setSelectedIndex(1);
            }
            if (selectKleren.getKlerenFoto() != null) {
                byte[] imageBytes;
                byte[] image = selectKleren.getKlerenFoto();
                ImageIcon icon = new ImageIcon(image);
                btnFoto.setIcon(icon);
            } else {
                btnFoto.setIcon(null);
            }
            if (selectKleren != null) {
                byte[] imageBytes;
                byte[] image = selectBoek.getBoekenFoto();
                ImageIcon icon = new ImageIcon(image);
                Boeken boek = selectBoek;
                txtAdvertentieTitel.setText(selectKleren.getSoortKleding());
                txtAdvertentieUitgeverij.setText(selectKleren.getSeizoen());
                txtAdvertentieAuteur.setText(selectKleren.getMaat());
                btnFoto.setIcon(icon);
            }

        }
        if ("selectSpeelgoed".equals(select)) {
            lblAdvertentieAuteur.setText("Leeftijd");
            lblAdvertentieCategorie.setText("Categorie");
            lblAdvertentieUitgeverij.setVisible(false);
            txtAdvertentieUitgeverij.setVisible(false);
            lblGeslacht.setVisible(true);
            cbxGeslacht.setVisible(true);
            txtOmschrijving.setText(selectSpeelgoed.getOmschrijving());
            if (selectSpeelgoed.getGeslacht()) {
                cbxGeslacht.setSelectedIndex(0);

            } else {
                cbxGeslacht.setSelectedIndex(1);
            }

            if (selectSpeelgoed.getSpeelgoedFoto() != null) {
                byte[] imageBytes;
                byte[] image = selectBoek.getBoekenFoto();
                ImageIcon icon = new ImageIcon(image);
                btnFoto.setIcon(icon);
            } else {
                btnFoto.setIcon(null);
            }
            if (selectSpeelgoed != null) {

                Speelgoed speel = selectSpeelgoed;
                txtAdvertentieTitel.setText(selectSpeelgoed.getTitel());
                txtAdvertentieAuteur.setText(selectSpeelgoed.getLeeftijd().toString());
                txtAdvertentieUitgeverij.setText(selectSpeelgoed.getCategorie());
            }

        }

    }

    private void ListboxOpvullen() {
        persoonService = new PersoonService();
        lstPersonen.setListData(persoonService.AllePersonenOphalen().toArray());
    }

    private void BoekListOpvullen() {
        lstBoeken.setListData(bookService.SelecteerBoek(selectPersoon.getId(), selectPersoon).toArray());

    }

    private void BabyListOpvullen() {

        lstBabySpullen.setListData(babyService.SelecteerBaby(selectPersoon.getId(), selectPersoon).toArray());

    }

    private void KlerenListOpvullen() {

        lstKleren.setListData(klerenService.SelecteerKleren(selectPersoon.getId(), selectPersoon).toArray());

    }

    private void SpeelgoedListOpvullen() {
        SpeelgoedService sp = new SpeelgoedService();
        lstSpeelgoed.setListData(sp.SelecteerSpeelgoed(selectPersoon.getId(), selectPersoon).toArray());

    }

    private void ClearPersoon() {
        selectPersoon = null;
        txtTitel.setText(null);
        txtVoornaam.setText(null);
        txtVoornaam.setText(null);
        txtFamilieNaam.setText(null);
        txtEmail.setText(null);
        txtWoonplaats.setText(null);
        txtWoonplaats.setText(null);
        txtUserName.setText(null);
        txtPassWord.setText(null);

    }

    private void ClearAdvertentie() {
        txtAdvertentieTitel.setText(null);
        txtAdvertentieAuteur.setText(null);
        txtAdvertentieUitgeverij.setText(null);
        txtOmschrijving.setText(null);
        btnFoto.setIcon(null);
    }

    private void ClearList() {
        lstBabySpullen.setListData(new Object[0]);
        lstBoeken.setListData(new Object[0]);
        lstKleren.setListData(new Object[0]);
        lstSpeelgoed.setListData(new Object[0]);
    }
    private void btnSelectBabyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectBabyActionPerformed
        ClearAdvertentie();
        selectBaby = (Babyspullen) lstBabySpullen.getSelectedValue();
        CBXVullen("selectBaby");
        DetailsVullen("selectBaby");

    }//GEN-LAST:event_btnSelectBabyActionPerformed

    private void btnEditPersoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPersoonActionPerformed

        if (selectPersoon != null) {
            selectPersoon.setAanspreekTitel(txtTitel.getText());
            selectPersoon.setVoornaam(txtVoornaam.getText());
            selectPersoon.setFamilienaam(txtFamilieNaam.getText());
            selectPersoon.setEmail(txtEmail.getText());
            selectPersoon.setWoonPlaats(txtWoonplaats.getText());
            selectPersoon.setUserName(txtUserName.getText());
            selectPersoon.setPassWord(txtPassWord.getText());
            PersoonService.PersoonUpdate(selectPersoon.getId(), selectPersoon);
        }
        ListboxOpvullen();
    }//GEN-LAST:event_btnEditPersoonActionPerformed

    private void btnAddPersoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersoonActionPerformed

        if (selectPersoon != null) {
            JOptionPane.showMessageDialog(this, "Deze gebruiker bestaat al indien, u een nieuw gebruiker wil toevoegen kies dan voor de Add knop nadat u alle velden heeft leeg gemaakt met de Clear knop");
        } else {

            Persoon p = new Persoon();
            p.setAanspreekTitel(txtTitel.getText());
            p.setVoornaam(txtVoornaam.getText());
            p.setFamilienaam(txtFamilieNaam.getText());
            p.setEmail(txtEmail.getText());
            p.setWoonPlaats(txtWoonplaats.getText());
            p.setUserName(txtUserName.getText());
            p.setPassWord(txtPassWord.getText());

            PersoonService.PersoonAdd(p);
        }
        ListboxOpvullen();
        ClearList();
        ClearPersoon();
    }//GEN-LAST:event_btnAddPersoonActionPerformed

    private void btnClearPersoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPersoonActionPerformed
        ClearPersoon();

    }//GEN-LAST:event_btnClearPersoonActionPerformed

    private void btnDeleteKlerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteKlerenActionPerformed

        Kleren kleren = new Kleren();
        kleren = (Kleren) lstKleren.getSelectedValue();

        if (kleren != null) {
            Kleren Kleren = kleren;
            KlerenService.KlerenDelete(kleren.getId());

        }
        KlerenListOpvullen();

    }//GEN-LAST:event_btnDeleteKlerenActionPerformed

    private void btnAddGebruiker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGebruiker2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddGebruiker2ActionPerformed

    private void btnSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFileActionPerformed
        JFileChooser dialog = new JFileChooser();
        dialog.showOpenDialog(this);
        String file = null;
        try {
            file = dialog.getSelectedFile().getAbsolutePath();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        ImageIcon icon = null;

        ImageIcon imageicon = new ImageIcon(file);

        if (imageicon != null) {

            if (imageicon.getIconWidth() > 60) {
                System.out.println(btnFoto.getWidth());
                icon = new ImageIcon(imageicon.getImage().getScaledInstance(300, -1, Image.SCALE_DEFAULT));
            } else {
                icon = imageicon;
            }
            btnFoto.setText(null);
            btnFoto.setIcon((Icon) icon);
        }

    }//GEN-LAST:event_btnSelectFileActionPerformed

    private void cbxGeslachtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGeslachtActionPerformed

    }//GEN-LAST:event_cbxGeslachtActionPerformed

    private void btnSelectSpeelgoedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectSpeelgoedActionPerformed
        ClearAdvertentie();
        selectSpeelgoed = (Speelgoed) lstSpeelgoed.getSelectedValue();
        CBXVullen("selectSpeelgoed");
        DetailsVullen("selectSpeelgoed");


    }//GEN-LAST:event_btnSelectSpeelgoedActionPerformed

    private void btnSelectBoekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectBoekActionPerformed
        ClearAdvertentie();
        selectBoek = (Boeken) lstBoeken.getSelectedValue();
        CBXVullen("selectBoek");
        DetailsVullen("selectBoek");


    }//GEN-LAST:event_btnSelectBoekActionPerformed

    private void btnSelectKlerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectKlerenActionPerformed
        ClearAdvertentie();
        selectKleren = (Kleren) lstKleren.getSelectedValue();
        CBXVullen("selectKleren");
        DetailsVullen("selectKleren");
        if (selectKleren != null) {


    }//GEN-LAST:event_btnSelectKlerenActionPerformed
    }
    private void btnSelectPeroonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectPeroonActionPerformed
        ClearAdvertentie();
        ClearList();
        selectPersoon = (Persoon) lstPersonen.getSelectedValue();

        if (selectPersoon != null) {
            Persoon Persoon = selectPersoon;
            txtTitel.setText(selectPersoon.getAanspreekTitel());
            txtVoornaam.setText(selectPersoon.getVoornaam());
            txtFamilieNaam.setText(selectPersoon.getFamilienaam());
            txtEmail.setText(selectPersoon.getEmail());
            txtWoonplaats.setText(selectPersoon.getWoonPlaats());
            txtUserName.setText(selectPersoon.getUserName());
            txtPassWord.setText(selectPersoon.getPassWord());

        }
        BoekListOpvullen();
        BabyListOpvullen();
        KlerenListOpvullen();
        SpeelgoedListOpvullen();
    }//GEN-LAST:event_btnSelectPeroonActionPerformed

    private void btnVerwijderFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerwijderFotoActionPerformed
        btnFoto.setIcon(null);
    }//GEN-LAST:event_btnVerwijderFotoActionPerformed

    private void btnDeletePersoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePersoonActionPerformed
        Persoon persoon = new Persoon();
        persoon = (Persoon) lstPersonen.getSelectedValue();

        if (persoon != null) {
            Persoon Persoon = persoon;
            PersoonService.PersoonDelete(persoon.getId());

        }
    }//GEN-LAST:event_btnDeletePersoonActionPerformed

    private void btnDeleteBoekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBoekActionPerformed
        Boeken boek = new Boeken();
        boek = (Boeken) lstBoeken.getSelectedValue();

        if (boek != null) {
            Boeken Boeken = boek;
            BoekService.BoekDelete(boek.getId());

        }
        BoekListOpvullen();
    }//GEN-LAST:event_btnDeleteBoekActionPerformed

    private void btnDeleteBabyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBabyActionPerformed
        Babyspullen baby = new Babyspullen();
        baby = (Babyspullen) lstBabySpullen.getSelectedValue();

        if (baby != null) {
            Babyspullen Babyspullen = baby;
            BabyService.BabyDelete(baby.getId());

        }
        BabyListOpvullen();
    }//GEN-LAST:event_btnDeleteBabyActionPerformed

    private void btnDeleteSpeelgoedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSpeelgoedActionPerformed
        Speelgoed speel = new Speelgoed();
        speel = (Speelgoed) lstSpeelgoed.getSelectedValue();

        if (speel != null) {
            Speelgoed Speel = speel;
            SpeelgoedService.SpeelgoedDelete(speel.getId());

        }
        SpeelgoedListOpvullen();
    }//GEN-LAST:event_btnDeleteSpeelgoedActionPerformed

    private void btnEditBabyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBabyActionPerformed
        if (selectBaby != null) {
            JOptionPane.showMessageDialog(this, "Gelieve eerst een advertentie te selecteren!");
        } else {

//            byte[] imageBytes;
//            byte[] image = selectBaby.getBabyspullenFoto();
            selectBaby.setTitel(txtAdvertentieTitel.getText());
            selectBaby.setLeeftijd(Integer.parseInt(txtAdvertentieAuteur.getText()));
            selectBaby.setCategorie(cbxCategorie.toString());
            selectBaby.setCategorie(txtAdvertentieUitgeverij.getText());
            selectBaby.setOmschrijving(txtOmschrijving.getText());
            selectBaby.setBabyspullenFoto(null);
            selectBaby.setGeslacht(Geslacht(cbxGeslacht.getSelectedIndex()));
            BabyService.BabyspullenUpdate(selectBaby.getId(), selectBaby);

        }
        BabyListOpvullen();
    }//GEN-LAST:event_btnEditBabyActionPerformed

    private void btnEditBoekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBoekActionPerformed
        if (selectBoek != null) {
            JOptionPane.showMessageDialog(this, "Gelieve eerst een advertentie te selecteren!");
        } else {

//            byte[] imageBytes;
//            byte[] image = selectBaby.getBabyspullenFoto();
            selectBoek.setTitel(txtAdvertentieTitel.getText());
            selectBoek.setAuteur(txtAdvertentieAuteur.getText());
            selectBoek.setCategorie(cbxCategorie.toString());
            selectBoek.setUitgeverij(txtAdvertentieUitgeverij.getText());
            selectBoek.setOmschrijving(txtOmschrijving.getText());
            selectBoek.setBoekenFoto(null);
            BoekService.BoekenUpdate(selectBoek.getId(), selectBoek);

        }
        BoekListOpvullen();
    }//GEN-LAST:event_btnEditBoekActionPerformed

    private void btnEditKlerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditKlerenActionPerformed
        if (selectKleren != null) {
            JOptionPane.showMessageDialog(this, "Gelieve eerst een advertentie te selecteren!");
        } else {

//            byte[] imageBytes;
//            byte[] image = selectBaby.getBabyspullenFoto();
            selectKleren.setSoortKleding(txtAdvertentieTitel.getText());
            selectKleren.setMaat(txtAdvertentieAuteur.getText());
            selectKleren.setSeizoen(cbxCategorie.toString());
            selectKleren.setOmschrijving(txtOmschrijving.getText());
            selectKleren.setGeslacht(Geslacht(cbxGeslacht.getSelectedIndex()));
            selectKleren.setKlerenFoto(null);

            KlerenService.KlerenUpdate(selectKleren.getId(), selectKleren);

        }
        KlerenListOpvullen();
    }//GEN-LAST:event_btnEditKlerenActionPerformed

    private void btnEditSpeelgoedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSpeelgoedActionPerformed
        if (selectSpeelgoed != null) {
            JOptionPane.showMessageDialog(this, "Gelieve eerst een advertentie te selecteren!");
        } else {

//            byte[] imageBytes;
//            byte[] image = selectBaby.getBabyspullenFoto();
            selectSpeelgoed.setTitel(txtAdvertentieTitel.getText());
            selectSpeelgoed.setLeeftijd(Integer.parseInt(txtAdvertentieAuteur.getText()));
            selectSpeelgoed.setCategorie(cbxCategorie.toString());
            selectSpeelgoed.setOmschrijving(txtOmschrijving.getText());
            selectSpeelgoed.setSpeelgoedFoto(null);
            selectSpeelgoed.setGeslacht(Geslacht(cbxGeslacht.getSelectedIndex()));
            SpeelgoedService.SpeelgoedUpdate(selectSpeelgoed.getId(), selectSpeelgoed);

        }
        SpeelgoedListOpvullen();
    }//GEN-LAST:event_btnEditSpeelgoedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeheerderUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeheerderUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeheerderUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeheerderUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeheerderUI1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGebruiker2;
    private javax.swing.JButton btnAddPersoon;
    private javax.swing.JButton btnClearPersoon;
    private javax.swing.JButton btnDelete2;
    private javax.swing.JButton btnDeleteBaby;
    private javax.swing.JButton btnDeleteBoek1;
    private javax.swing.JButton btnDeleteKleren;
    private javax.swing.JButton btnDeletePersoon;
    private javax.swing.JButton btnDeleteSpeelgoed;
    private javax.swing.JButton btnEditBaby;
    private javax.swing.JButton btnEditBoek1;
    private javax.swing.JButton btnEditKleren;
    private javax.swing.JButton btnEditPersoon;
    private javax.swing.JButton btnEditSpeelgoed;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnSelectBaby;
    private javax.swing.JButton btnSelectBoek;
    private javax.swing.JButton btnSelectFile;
    private javax.swing.JButton btnSelectKleren;
    private javax.swing.JButton btnSelectPeroon;
    private javax.swing.JButton btnSelectSpeelgoed;
    private javax.swing.JButton btnVerwijderFoto;
    private javax.swing.JComboBox cbxCategorie;
    private javax.swing.JComboBox cbxGeslacht;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblAanspreekTitel1;
    private javax.swing.JLabel lblAanspreekTitel2;
    private javax.swing.JLabel lblAanspreekTitel4;
    private javax.swing.JLabel lblAanspreekTitel5;
    private javax.swing.JLabel lblAchtergrond;
    private javax.swing.JLabel lblAdvertentieAuteur;
    private javax.swing.JLabel lblAdvertentieCategorie;
    private javax.swing.JLabel lblAdvertentieUitgeverij;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblFamilieNaam;
    private javax.swing.JLabel lblFamilieNaam2;
    private javax.swing.JLabel lblGeslacht;
    private javax.swing.JLabel lblPassWord;
    private javax.swing.JLabel lblPassWord2;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserName2;
    private javax.swing.JLabel lblVoornaam;
    private javax.swing.JLabel lblVoornaam2;
    private javax.swing.JLabel lblWoonplaats;
    private javax.swing.JLabel lblWoonplaats2;
    private javax.swing.JList lstBabySpullen;
    private javax.swing.JList lstBoeken;
    private javax.swing.JList lstKleren;
    private javax.swing.JList lstPersonen;
    private javax.swing.JList lstSpeelgoed;
    private javax.swing.JTextField txtAanspreekTitel2;
    private javax.swing.JTextField txtAdvertentieAuteur;
    private javax.swing.JTextField txtAdvertentieTitel;
    private javax.swing.JTextField txtAdvertentieUitgeverij;
    private javax.swing.JButton txtEditGebruiker3;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtFamilieNaam;
    private javax.swing.JTextField txtFamilieNaam2;
    private javax.swing.JTextArea txtOmschrijving;
    private javax.swing.JTextField txtPassWord;
    private javax.swing.JTextField txtPassWord2;
    private javax.swing.JTextField txtTitel;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserName2;
    private javax.swing.JTextField txtVoornaam;
    private javax.swing.JTextField txtVoornaam2;
    private javax.swing.JTextField txtWoonplaats;
    private javax.swing.JTextField txtWoonplaats2;
    // End of variables declaration//GEN-END:variables
}
